### ISSUE TITLE
Missing Apache Ant depedency

### ISSUE THREAD

**Issue by fabiodrg** [specs-feup/specs-java-libs#2]
I followed the instructions presented in this repo for working on Clava locally but had problems in `Utilities/DeployUtils.java` because `import org.apache` could not be resolved. I downloaded ready to use binaries (https://ant.apache.org/bindownload.cgi) and imported the main JAR, which solved the dependency problem.
I am not sure if I missed anything in the process, or the configuration instructions are missing this step?

https://github.com/specs-feup/specs-java-libs/blob/cb7b405ebadd66456f0af66b3c790ed584554e8a/EclipseUtils/src/pt/up/fe/specs/eclipse/Utilities/DeployUtils.java#L24

**Comment by Sleepy105** [comment]
Did you eventually solve this mystery?

**Comment by fabiodrg** [comment]
I have to repeat the process and try to replicate it

**Comment by joaobispo** [comment]
I suspect it might have to do with Ivy dependencies. For some reason, sometimes when importing a project in Eclipse, it "looses" its connection with the ivy.xml file, and you need to right-click on the file and select "Add Ivy Library...". I have not found out why this happens.

**Comment by joaobispo** [comment]
Closing this issue, it was opened a long time ago and a possible solution was provided.
